### ISSUE TITLE
another fakeplayer bug with shaders

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#21] opened 2024-08-24 15:45 UTC
**Describe the bug**

**To Reproduce**
1. connect to a server
2. enable fakeplayer
3. enable marble shadersd
4. walk around the fakeplayer

**Expected behavior**
shader buggin

**Screenshots**
(https://streamable.com/dov7zg)

![image](https://github.com/user-attachments/assets/530f9c37-d185-4986-bfd8-121069914b68)
my shader settings

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment] 2024-08-30 15:53
Duplicate of #20

**Closed as completed by pastimee** 2024-08-30 15:53 UTC
Labels: bug
