### ISSUE TITLE
Textures getting fucked

### ISSUE THREAD

**Issue by DaggerGotAim** [ShorelineLLC/issues#59] opened 2024-09-10 19:13 UTC
it keeps happening and not sure why on 2b https://cdn.discordapp.com/attachments/1246224105645150331/1283128491688067135/Base_Profile_Screenshot_2024.09.10_-_13.14.00.62.png?ex=66e1de07&is=66e08c87&hm=e0c38f7b551bd80ceb70fca0dd17e98414893a6d175ec5dad2eef9e960c6f484&

**Comment by pastimee** [comment] 2024-09-10 22:21
Duplicate of #10

**Closed as completed by pastimee** 2024-09-10 22:21 UTC
Labels: bug
