### ISSUE TITLE
Crash during pvp, (i think the same as Jaxui)

### ISSUE THREAD

**Issue by rarelib** [ShorelineLLC/issues#26] opened 2024-08-25 20:00 UTC
Crash Log during grimcc.

[crash-2024-08-25_14.55.59-client.txt](https://github.com/user-attachments/files/16741748/crash-2024-08-25_14.55.59-client.txt)

**Comment by pastimee** [comment] 2024-08-25 21:30
Duplicate of #22, Fixed in 18da245

**Closed as completed by pastimee** 2024-08-25 21:30 UTC
Labels: bug
