### ISSUE TITLE
big banners in my fucking screen

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#33] opened 2024-08-30 13:13 UTC
**Describe the bug**
all i see is banners everywhere

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/7cbb86b9-3402-419e-949b-78e91ce81de3)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment] 2024-08-30 15:53
Duplicate of #20

**Closed as completed by pastimee** 2024-08-30 15:53 UTC
Labels: bug
